#springboot+mybatis+SpringSecurity
server:
  port: 8090
logging:
  file: ../logs/lemoon.log
  level:
    org:
      springframework:
        security: INFO
#  oauth2:
#    client:
#      clientId: SampleClientId
#      clientSecret: secret
#      accessTokenUri: http://localhost:8081/auth/oauth/token
#      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8081/auth/user/me
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    cookie:
      name: UISESSION
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: true
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    check-template: true
    enabled: true
    check-template-location: true
    mode: html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3305/aliyun?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource


  jackson:
    serialization:
      indent_output: true