
#springboot+mybatis+SpringSecurity
server:
  port: 8090
#servlet.context-path: /hello
logging:
  file: Users/24520/IdeaProjects/valpro/lemoon.log
  level:
    org:
      springframework:
        security: INFO


security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      clientId: SampleClientId
#      clientSecret: secret
#      accessTokenUri: http://localhost:8081/auth/oauth/token
#      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8081/auth/user/me

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  session:
    cookie:
      name: UISESSION
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3305/rent?characterEncoding=utf-8&useSSL=false
    username: root
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
  jackson:
    serialization:
      indent_output: true
  profiles:
    include: