server:
  port: 8099
logging:
  file: ../logs/lemoon.log
  level:
    org:
      springframework: debug
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  session:
    cookie:
      name: UISESSION
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**,/images/**,/js/**,/css/**
  thymeleaf:
    cache: false
    encoding: utf-8
    check-template: true
    enabled: true
    check-template-location: true
    mode: html
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/valpro
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      indent_output: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/**,/webjars/**,classpath:/static/js/,classpath:/templates/


#应用名称
  dubbo:
    admin:
      root:
        password: root
      guest:
        password: guest
    application:
      #注册在注册中心的名称，唯一标识，请勿重复
      id: auth-branch
      name: auth-branch
    #注册中心地址，zookeeper集群，启动输出可以看见链接了多个
    #单zookeeper服务：zookeeper://127.0.0.1:2181
    registry:
      address: zookeeper://192.168.24.188:2181?backup=192.168.24.188:2180,192.168.24.188:2182
    #暴露服务方式
    protocol:
      id: dubbo
      #默认名称，勿修改
      name: dubbo
      #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
      port: 20881
      status : server
    #调用dubbo组建扫描的项目路径
    scan: com.security.valpro.service