server:
  port: 8090
logging:
  file: ../logs/lemoon.log
  level:
    org:
      springframework:
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  session:
    cookie:
      name: UISESSION
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**,/images/**,/js/**,/css/**
  thymeleaf:
    cache: false
    encoding: utf-8
    check-template: true
    enabled: true
    check-template-location: true
    mode: html
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/valpro
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      indent_output: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/**,/webjars/**,classpath:/static/js/,classpath:/templates/
